import { useRef, useState } from 'react'
import { ReactFlow, Background, Controls, MiniMap, Handle, Position, useNodesState } from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { FileText, Sparkles, Share2, Plus, Newspaper, Link2, WandSparkles, GripVertical, ImagePlus, Type, Search, Upload, Eye, Maximize2, X as XIcon, Trash2 } from 'lucide-react'
import './App.css'
const seed=[
{id:'headline',kind:'title',label:'TITLE',title:'정부, 도심 교통 혁신 위한 자율주행 시범사업 확대'},
{id:'lead',kind:'text',label:'LEAD',title:'정부, 도심 교통 혁신 위한 자율주행 시범사업 확대',body:'정부가 내년부터 자율주행 대중교통 시범사업을 전국 주요 도시로 확대한다. 시민의 이동 편의성을 높이고 미래 교통 산업의 기반을 마련한다는 계획이다.'},
{id:'fact',kind:'text',label:'FACT',title:'시범 지역 5곳 → 12곳',body:'국토교통부는 현재 5개 지역에서 운영 중인 자율주행 시범운행지구를 12개 지역으로 확대할 예정이라고 밝혔다.'},
{id:'quote',kind:'text',label:'QUOTE',title:'“일상에서 체감할 변화”',body:'정부 관계자는 “기술 실증을 넘어 시민들이 일상에서 직접 체감할 수 있는 서비스로 발전시키겠다”고 말했다.'},
{id:'context',kind:'text',label:'CONTEXT',title:'상용화 경쟁 가속',body:'국내 자율주행 시장은 규제 완화와 기술 투자 확대에 힘입어 빠르게 성장하고 있다. 업계는 이번 사업이 상용화를 앞당길 것으로 보고 있다.'},
{id:'outlook',kind:'text',label:'OUTLOOK',title:'2027년 정식 서비스 목표',body:'정부는 시범사업 결과를 바탕으로 안전 기준과 운영 지침을 정비해 2027년부터 단계적인 정식 서비스를 추진할 계획이다.'}]
const X=300,GAP=220,makeNodes=()=>seed.map((n,i)=>({id:n.id,position:{x:X,y:65+i*GAP},data:{...n,index:i},type:'article'}))
function InsertMenu({data}){const [open,setOpen]=useState(false);return <div className="insertWrap nodrag nopan"><button className="insertPlus" onClick={()=>setOpen(v=>!v)} aria-label="노드 삽입"><Plus size={14}/></button>{open&&<div className="insertMenu"><button onClick={()=>{data.insert(data.index+1,'text');setOpen(false)}}><Type size={13}/>글</button><button onClick={()=>{data.insert(data.index+1,'image');setOpen(false)}}><ImagePlus size={13}/>이미지</button></div>}</div>}
function ArticleNode({data}){const edit=(k,v)=>data.update(data.id,k,v);if(data.kind==='title')return <div className="node titleNode"><Handle type="target" position={Position.Top} isConnectable={false}/><div className="nodeTop"><div className="tag title">TITLE · 기사 제목</div><GripVertical size={15}/></div><textarea className="headlineInput nodrag nopan" value={data.title} onChange={e=>edit('title',e.target.value)}/><div className="nodefoot"><span>기사 제목 전용 노드</span><span>본문과 독립 편집</span></div><Handle type="source" position={Position.Bottom} isConnectable={false}/><InsertMenu data={data}/></div>;if(data.kind==='image')return <div className="node imageNode"><Handle type="target" position={Position.Top} isConnectable={false}/><div className="nodeTop"><div className="tag image">IMAGE</div><GripVertical size={15}/></div><div className="imagePlaceholder"><ImagePlus/><b>이미지 블록</b><span>AI 이미지 생성 연결 예정</span></div><input className="nodeInput nodrag nopan" value={data.caption||''} placeholder="이미지 캡션…" onChange={e=>edit('caption',e.target.value)}/><Handle type="source" position={Position.Bottom} isConnectable={false}/><InsertMenu data={data}/></div>;return <div className="node"><Handle type="target" position={Position.Top} isConnectable={false}/><div className="nodeTop"><div className={'tag '+data.label.toLowerCase()}>{String(data.index+1).padStart(2,'0')} · {data.label}</div><GripVertical size={15}/></div><input className="nodeTitle nodrag nopan" value={data.title} onChange={e=>edit('title',e.target.value)}/><textarea className="nodeBody nodrag nopan" value={data.body} onChange={e=>edit('body',e.target.value)}/><div className="nodefoot"><span>직접 편집 가능</span><span>위아래로 이동</span></div><Handle type="source" position={Position.Bottom} isConnectable={false}/><InsertMenu data={data}/></div>}
function EvidenceNode({data}){return <div className="evidenceNode"><Handle type="target" position={Position.Left}/><Handle type="source" position={Position.Right}/><b><Link2 size={13}/>{data.title}</b><span>{data.meta}</span></div>}
const nodeTypes={article:ArticleNode,evidence:EvidenceNode}
function App(){
 const [nodes,setNodes,onNodesChange]=useNodesState(makeNodes());const [split,setSplit]=useState(48),[dropIndex,setDropIndex]=useState(null);const shell=useRef(null)
 const update=(id,k,v)=>setNodes(ns=>ns.map(n=>n.id===id?{...n,data:{...n.data,[k]:v}}:n))
 const normalize=arr=>arr.map((n,i)=>({...n,position:{x:X,y:65+i*GAP},data:{...n.data,index:i}}))
 const insert=(at,kind)=>setNodes(ns=>{const ordered=[...ns].sort((a,b)=>a.position.y-b.position.y);const id=kind+'-'+Date.now();const data=kind==='image'?{kind:'image',label:'IMAGE',caption:''}:{kind:'text',label:'BODY',title:'새 문단',body:'내용을 입력하세요.'};ordered.splice(at,0,{id,type:'article',position:{x:X,y:0},data});return normalize(ordered)})
 const ordered=[...nodes].sort((a,b)=>a.position.y-b.position.y)
 const evidence=ordered.flatMap((n,i)=>n.data.kind==='title'?[]:[{id:'ev-'+n.id,type:'evidence',position:{x:i%2?650:20,y:n.position.y+35},data:{title:n.data.kind==='image'?'현장 사진 원본':i%3===0?'국토부 정책보고서':i%3===1?'관계자 인터뷰':'서울시 보도자료',meta:i%3===0?'PDF · p.12–18':i%3===1?'AUDIO · 14:32–16:10':'WEB · 원문'}}])
 const hydrated=nodes.map(n=>({...n,data:{...n.data,id:n.id,update,insert}})).concat(evidence)
 const flow=ordered.slice(0,-1).map((n,i)=>({id:'e-'+n.id,source:n.id,target:ordered[i+1].id,type:'smoothstep',className:'articleEdge'}))
 const evidenceEdges=evidence.map(ev=>{const target=ev.id.slice(3);return {id:'link-'+ev.id,source:ev.position.x<300?ev.id:target,target:ev.position.x<300?target:ev.id,type:'smoothstep',className:'evidenceEdge'}})
 const edges=[...flow,...evidenceEdges]
 const drag=(_,n)=>setDropIndex(Math.max(0,Math.min(nodes.length-1,Math.round((n.position.y-65)/GAP))));const snap=(_,d)=>{const a=ordered.filter(n=>n.id!==d.id);a.splice(dropIndex??0,0,d);setNodes(normalize(a));setDropIndex(null)}
 const resize=e=>{e.preventDefault();const move=ev=>{const r=shell.current.getBoundingClientRect();setSplit(Math.max(30,Math.min(70,(ev.clientX-r.left)/r.width*100)))};const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up)};addEventListener('pointermove',move);addEventListener('pointerup',up)}
 return <div className="app"><header><div className="brand"><div className="mark"><Share2 size={18}/></div><b>NodeArticle</b><span>STORY COMPOSER</span></div><div className="topNav"><button className="selected">작성</button><button>자료</button><button>검증</button><button>히스토리</button><button className="export">내보내기⌄</button><i>J</i></div></header><aside className="sourcesPanel"><div className="sideTitle"><b>Sources</b><button><Plus size={14}/> 추가</button></div><div className="sourceTabs"><b>전체</b><span>문서</span><span>오디오</span><span>웹</span><span>이미지</span></div><div className="sourceSearch"><Search size={14}/>자료 검색...</div><div className="sourceList"><div>📄 <span><b>서울시 보도자료</b><small>PDF · 2.3MB</small></span></div><div>🎵 <span><b>자율주행 인터뷰_김정호.mp3</b><small>오디오 · 48:12</small></span></div><div>📕 <span><b>국토부 자율주행 정책보고서</b><small>PDF · 5.1MB</small></span></div><div>🖼️ <span><b>서울시 자율주행 시범운행.jpg</b><small>이미지 · 1.2MB</small></span></div><div>🟣 <span><b>관련 기사 모음</b><small>웹페이지 · 12개</small></span></div><div>📑 <span><b>업계 전문가 인터뷰</b><small>문서 · 32KB</small></span></div></div><div className="sourceDrop"><Plus size={15}/> 더 많은 자료 추가<div><Upload size={18}/> 🔗</div><small>또는 파일을 드래그하세요</small></div></aside>
 <main><div className="storyBar"><b>‹</b><strong>서울시 자율주행 버스 시범운행 시작</strong><span>◉ 저장됨 · 10:24</span></div><div className="workspace" ref={shell}><section className="graphPane graphCanvasPane"><div className="paneHead"><b>Article Graph</b><span>↖　✋　100%　⌕　⛶　　+ 노드 추가</span></div><div className="flowWrap">{dropIndex!==null&&<div className="dropMarker" style={{top:65+dropIndex*GAP-12}}><span>여기에 삽입</span></div>}<ReactFlow nodes={hydrated} edges={edges} onNodesChange={onNodesChange} onNodeDrag={(e,n)=>{if(n.type==='article')drag(e,n)}} onNodeDragStop={(e,n)=>{if(n.type==='article')snap(e,n)}} nodeTypes={nodeTypes} nodesConnectable={false} fitView fitViewOptions={{padding:.08}}><Background variant="dots" gap={22} size={1.2}/><MiniMap pannable zoomable/><Controls/></ReactFlow></div></section><div className="splitter" onPointerDown={resize}><div/></div>
 <section className="articlePane"><div className="paneHead"><b>Live Article</b><span>◉ 미리보기　⛶ 전체화면</span></div><article><div className="kicker">TECH · MOBILITY</div><h2>{ordered.find(n=>n.data.kind==='title')?.data.title||'제목 없음'}</h2><div className="by">김아름 기자 · DRAFT</div>{ordered.filter(x=>x.data.kind!=='title').map((x,i)=>x.data.kind==='image'?<figure key={x.id}><div className="articleImage"><ImagePlus/><span>AI IMAGE</span></div><figcaption>{x.data.caption||'이미지 캡션'}</figcaption></figure>:<div className="articlePara" key={x.id}><small>{String(i+1).padStart(2,'0')} · {x.data.label}</small><p>{x.data.body}</p></div>)}</article></section><section className="propertiesPanel"><div className="propHead"><b>Node Properties</b><XIcon size={16}/></div><div className="propTabs"><b>기본 정보</b><span>연결된 자료</span></div><label>노드 타입</label><div className="propSelect"><i/> FACT⌄</div><label>노드 요약명 <small>(편집용, 기사에 표시되지 않음)</small></label><input value="시범운행 구간과 운영 계획" readOnly/><label>본문 내용 <small>(실제 기사에 포함되는 텍스트)</small></label><textarea value="서울시는 시청에서 청계천, 서울역을 잇는 구간(총 7.2km)에서 자율주행 버스를 시범 운행한다. 평일 기준 하루 10회 운행되며, 일반 시민도 무료로 탑승할 수 있다." readOnly/><div className="linkedHead"><b>연결된 근거 자료 (4)</b><button>+ 추가</button></div><div className="linkedList"><div>🗺️ 노선 지도 <XIcon/></div><div>📕 국토부 정책보고서 <XIcon/></div><div>📘 운영 계획안 <XIcon/></div><div>🎵 관계자 인터뷰 <XIcon/></div></div><label>노드 색상</label><div className="colors"><i/><i/><i/><i/><i/><i/></div><div className="propActions"><button>↑　위로 이동</button><button>↓　아래로 이동</button><button>▣　복제</button><button className="danger"><Trash2 size={14}/> 노드 삭제</button></div></section></div><footer><span><b>{nodes.length}</b> 블록 · 자동 연결</span><span>글과 이미지가 하나의 기사 흐름을 구성합니다</span></footer></main></div>
}
export default App
