import { useRef, useState } from 'react'
import { ReactFlow, Background, Controls, Handle, Position, useNodesState } from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { FileText, Sparkles, Share2, Plus, Newspaper, Link2, WandSparkles, GripVertical, ImagePlus, Type } from 'lucide-react'
import './App.css'
const seed=[
{id:'lead',kind:'text',label:'LEAD',title:'정부, 도심 교통 혁신 위한 자율주행 시범사업 확대',body:'정부가 내년부터 자율주행 대중교통 시범사업을 전국 주요 도시로 확대한다. 시민의 이동 편의성을 높이고 미래 교통 산업의 기반을 마련한다는 계획이다.'},
{id:'fact',kind:'text',label:'FACT',title:'시범 지역 5곳 → 12곳',body:'국토교통부는 현재 5개 지역에서 운영 중인 자율주행 시범운행지구를 12개 지역으로 확대할 예정이라고 밝혔다.'},
{id:'quote',kind:'text',label:'QUOTE',title:'“일상에서 체감할 변화”',body:'정부 관계자는 “기술 실증을 넘어 시민들이 일상에서 직접 체감할 수 있는 서비스로 발전시키겠다”고 말했다.'},
{id:'context',kind:'text',label:'CONTEXT',title:'상용화 경쟁 가속',body:'국내 자율주행 시장은 규제 완화와 기술 투자 확대에 힘입어 빠르게 성장하고 있다. 업계는 이번 사업이 상용화를 앞당길 것으로 보고 있다.'},
{id:'outlook',kind:'text',label:'OUTLOOK',title:'2027년 정식 서비스 목표',body:'정부는 시범사업 결과를 바탕으로 안전 기준과 운영 지침을 정비해 2027년부터 단계적인 정식 서비스를 추진할 계획이다.'}]
const X=70,GAP=220,makeNodes=()=>seed.map((n,i)=>({id:n.id,position:{x:X,y:65+i*GAP},data:{...n,index:i},type:'article'}))
function InsertMenu({data}){const [open,setOpen]=useState(false);return <div className="insertWrap nodrag nopan"><button className="insertPlus" onClick={()=>setOpen(v=>!v)} aria-label="노드 삽입"><Plus size={14}/></button>{open&&<div className="insertMenu"><button onClick={()=>{data.insert(data.index+1,'text');setOpen(false)}}><Type size={13}/>글</button><button onClick={()=>{data.insert(data.index+1,'image');setOpen(false)}}><ImagePlus size={13}/>이미지</button></div>}</div>}
function ArticleNode({data}){const edit=(k,v)=>data.update(data.id,k,v);if(data.kind==='image')return <div className="node imageNode"><Handle type="target" position={Position.Top} isConnectable={false}/><div className="nodeTop"><div className="tag image">IMAGE</div><GripVertical size={15}/></div><div className="imagePlaceholder"><ImagePlus/><b>이미지 블록</b><span>AI 이미지 생성 연결 예정</span></div><input className="nodeInput nodrag nopan" value={data.caption||''} placeholder="이미지 캡션…" onChange={e=>edit('caption',e.target.value)}/><Handle type="source" position={Position.Bottom} isConnectable={false}/><InsertMenu data={data}/></div>;return <div className="node"><Handle type="target" position={Position.Top} isConnectable={false}/><div className="nodeTop"><div className={'tag '+data.label.toLowerCase()}>{String(data.index+1).padStart(2,'0')} · {data.label}</div><GripVertical size={15}/></div><input className="nodeTitle nodrag nopan" value={data.title} onChange={e=>edit('title',e.target.value)}/><textarea className="nodeBody nodrag nopan" value={data.body} onChange={e=>edit('body',e.target.value)}/><div className="nodefoot"><span>직접 편집 가능</span><span>위아래로 이동</span></div><Handle type="source" position={Position.Bottom} isConnectable={false}/><InsertMenu data={data}/></div>}
const nodeTypes={article:ArticleNode}
function App(){
 const [nodes,setNodes,onNodesChange]=useNodesState(makeNodes());const [split,setSplit]=useState(48),[dropIndex,setDropIndex]=useState(null);const shell=useRef(null)
 const update=(id,k,v)=>setNodes(ns=>ns.map(n=>n.id===id?{...n,data:{...n.data,[k]:v}}:n))
 const normalize=arr=>arr.map((n,i)=>({...n,position:{x:X,y:65+i*GAP},data:{...n.data,index:i}}))
 const insert=(at,kind)=>setNodes(ns=>{const ordered=[...ns].sort((a,b)=>a.position.y-b.position.y);const id=kind+'-'+Date.now();const data=kind==='image'?{kind:'image',label:'IMAGE',caption:''}:{kind:'text',label:'BODY',title:'새 문단',body:'내용을 입력하세요.'};ordered.splice(at,0,{id,type:'article',position:{x:X,y:0},data});return normalize(ordered)})
 const hydrated=nodes.map(n=>({...n,data:{...n.data,id:n.id,update,insert}}));const ordered=[...nodes].sort((a,b)=>a.position.y-b.position.y);const edges=ordered.slice(0,-1).map((n,i)=>({id:'e-'+n.id,source:n.id,target:ordered[i+1].id,type:'smoothstep'}))
 const drag=(_,n)=>setDropIndex(Math.max(0,Math.min(nodes.length-1,Math.round((n.position.y-65)/GAP))));const snap=(_,d)=>{const a=ordered.filter(n=>n.id!==d.id);a.splice(dropIndex??0,0,d);setNodes(normalize(a));setDropIndex(null)}
 const resize=e=>{e.preventDefault();const move=ev=>{const r=shell.current.getBoundingClientRect();setSplit(Math.max(30,Math.min(70,(ev.clientX-r.left)/r.width*100)))};const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up)};addEventListener('pointermove',move);addEventListener('pointerup',up)}
 return <div className="app"><header><div className="brand"><div className="mark"><Share2 size={18}/></div><b>NodeArticle</b><span>STORY COMPOSER</span></div><button className="primary"><Sparkles size={16}/> 기사 생성</button></header><aside><div className="new"><Plus size={17}/> 새 기사</div><nav><div className="navtitle">WORKSPACE</div><a className="active"><Newspaper/>스토리 에디터</a><a><FileText/>소스 라이브러리</a><a><WandSparkles/>AI 생성 기록</a></nav></aside>
 <main><section className="topline"><div><div className="crumb">STORIES / DRAFT</div><h1>자율주행 시범사업 확대</h1><p>노드에서 바로 쓰고, 재배열하고, 노드 사이 + 버튼으로 새 블록을 삽입하세요.</p></div></section><section className="sourcebar"><div><Link2/><span><b>연결된 소스 3개</b><small>보도자료 · 브리핑 · 시장 리포트</small></span></div></section>
 <div className="workspace" ref={shell}><section className="graphPane" style={{width:split+'%'}}><div className="paneHead"><b>ARTICLE FLOW</b><span>+ 버튼 → 글 / 이미지 선택</span></div><div className="flowWrap">{dropIndex!==null&&<div className="dropMarker" style={{top:65+dropIndex*GAP-12}}><span>여기에 삽입</span></div>}<ReactFlow nodes={hydrated} edges={edges} onNodesChange={onNodesChange} onNodeDrag={drag} onNodeDragStop={snap} nodeTypes={nodeTypes} nodesConnectable={false} fitView fitViewOptions={{padding:.08}}><Background gap={24} size={1}/><Controls/></ReactFlow></div></section><div className="splitter" onPointerDown={resize}><div/></div>
 <section className="articlePane" style={{width:(100-split)+'%'}}><div className="paneHead"><b>LIVE ARTICLE</b><span>편집 내용 실시간 반영</span></div><article><div className="kicker">TECH · MOBILITY</div><h2>{ordered.find(n=>n.data.kind==='text')?.data.title}</h2><div className="by">김아름 기자 · DRAFT</div>{ordered.map((x,i)=>x.data.kind==='image'?<figure key={x.id}><div className="articleImage"><ImagePlus/><span>AI IMAGE</span></div><figcaption>{x.data.caption||'이미지 캡션'}</figcaption></figure>:<div className="articlePara" key={x.id}><small>{String(i+1).padStart(2,'0')} · {x.data.label}</small><p>{x.data.body}</p></div>)}</article></section></div><footer><span><b>{nodes.length}</b> 블록 · 자동 연결</span><span>글과 이미지가 하나의 기사 흐름을 구성합니다</span></footer></main></div>
}
export default App
