import {useMemo,useState} from 'react'
import {ReactFlow,Background,Controls,MiniMap,Handle,Position} from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import './App.css'
import {Plus,Search,Upload,X,Trash2,FileText,Music,Image as ImageIcon,Link2} from 'lucide-react'

const story=[
{id:'title',type:'article',position:{x:260,y:40},data:{kind:'title',role:'TITLE',summary:'서울시, 자율주행 버스 시범운행 시작',body:''}},
{id:'lead',type:'article',position:{x:260,y:190},data:{role:'LEAD',summary:'시범운행 시작과 의미',body:'서울시가 26일부터 자율주행 버스 시범운행을 시작했다. 도심 교통의 새로운 전환점으로, 시민들이 직접 자율주행 기술을 체험할 수 있는 첫 사례다.'}},
{id:'fact',type:'article',position:{x:260,y:410},data:{role:'FACT',summary:'시범운행 구간과 운영 계획',body:'서울시는 시청에서 청계천, 서울역을 잇는 구간(총 7.2km)에서 자율주행 버스를 시범 운행한다. 평일 기준 하루 10회 운행되며, 일반 시민도 무료로 탑승할 수 있다.'}},
{id:'image',type:'article',position:{x:260,y:650},data:{kind:'image',role:'IMAGE',summary:'서울시 자율주행 버스 현장 사진',caption:'서울시 자율주행 버스가 청계천 인근을 주행하고 있다. (사진=서울시)'}},
{id:'quote',type:'article',position:{x:260,y:890},data:{role:'QUOTE',summary:'시민 체감이 가장 중요합니다',body:'서울시 교통정책과 김정호 과장은 인터뷰에서 “기술도 중요하지만, 시민들이 실제로 체험할 수 있는 안전성과 편의성이 핵심”이라고 말했다.'}},
{id:'context',type:'article',position:{x:260,y:1120},data:{role:'CONTEXT',summary:'국내외 자율주행 정책 동향',body:'국토부는 올해 자율주행 상용화를 위한 규제를 정비하고 있으며, 해외 주요 도시들도 유사한 시범사업을 확대하고 있다.'}},
{id:'outlook',type:'article',position:{x:260,y:1340},data:{role:'OUTLOOK',summary:'남은 과제와 향후 전망',body:'전문가들은 기술적 완성도와 시민 수용성이 확보된다면, 서울시는 이번 시범운행을 통해 수집한 데이터를 바탕으로 운영을 점진적으로 확대할 계획이다.'}}
]
const ev=[['e1',30,235,'서울시 보도자료','PDF · p.1–3','lead'],['e2',650,250,'관련 기사 모음','웹 · 3개 기사','lead'],['e3',25,470,'국토부 정책보고서','PDF · p.12–18','fact'],['e4',650,440,'노선 지도','서울시 제공','fact'],['e5',650,525,'운영 계획안','내부 문서','fact'],['e6',30,720,'현장 사진','서울시 제공','image'],['e7',20,950,'김정호 과장 인터뷰','14:32–16:10','quote'],['e8',650,950,'인터뷰 전문 텍스트','자동 전사본','quote'],['e9',30,1180,'해외 사례 기사','2개 기사','context'],['e10',650,1180,'전문가 의견','업계 전문가 인터뷰','context']]
const colors={TITLE:'#fb7185',LEAD:'#54c79a',FACT:'#f5b82e',IMAGE:'#9b6cf3',QUOTE:'#5797ed',CONTEXT:'#26abc0',OUTLOOK:'#718096'}
function ArticleNode({data}){let c=colors[data.role];return <div className={'articleNode '+data.role.toLowerCase()} style={{'--c':c}}><Handle type="target" position={Position.Top}/><div className="badge">{data.role}</div><b>{data.summary}</b>{data.kind==='image'?<div className="photo"><span>서울 도심을 달리는<br/>자율주행 버스</span></div>:data.kind!=='title'&&<p>{data.body}</p>} {data.caption&&<small>{data.caption}</small>}<Handle type="source" position={Position.Bottom}/></div>}
function EvidenceNode({data}){return <div className="evidence"><Handle type="target" position={Position.Left}/><Handle type="source" position={Position.Right}/><b><Link2 size={12}/>{data.title}</b><span>{data.meta}</span></div>}
const nodeTypes={article:ArticleNode,evidence:EvidenceNode}
function Sources(){return <aside className="sources"><div className="panelTitle"><b>Sources</b><button><Plus/> 추가</button></div><div className="tabs"><b>전체</b><span>문서</span><span>오디오</span><span>웹</span><span>이미지</span></div><div className="search"><Search/>자료 검색...</div><div className="files"><div>📄<span><b>서울시 보도자료</b><small>PDF · 2.3MB</small></span></div><div>🎵<span><b>자율주행 인터뷰_김정호.mp3</b><small>오디오 · 48:12</small></span></div><div>📕<span><b>국토부 자율주행 정책보고서</b><small>PDF · 5.1MB</small></span></div><div>🖼️<span><b>서울시 자율주행 시범운행.jpg</b><small>이미지 · 1.2MB</small></span></div><div>🟣<span><b>관련 기사 모음</b><small>웹페이지 · 12개</small></span></div><div>📑<span><b>업계 전문가 인터뷰</b><small>문서 · 32KB</small></span></div></div><div className="drop"><Plus/> 더 많은 자료 추가<div>▣　▶　🔗</div><small>또는 파일을 드래그하세요</small></div></aside>}
function Properties(){return <aside className="properties"><div className="panelTitle"><b>Node Properties</b><X/></div><div className="propTabs"><b>기본 정보</b><span>연결된 자료</span></div><label>노드 타입</label><div className="select"><i/> FACT　⌄</div><label>노드 요약명<small>편집용, 기사에 표시되지 않음</small></label><input value="시범운행 구간과 운영 계획" readOnly/><label>본문 내용<small>실제 기사에 포함되는 텍스트</small></label><textarea value={story[2].data.body} readOnly/><div className="linked"><b>연결된 근거 자료 (4)</b><button>+ 추가</button></div><div className="links"><div>🗺️ 노선 지도　×</div><div>📕 국토부 정책보고서　×</div><div>📘 운영 계획안　×</div><div>🎵 관계자 인터뷰　×</div></div><label>노드 색상</label><div className="dots">{Object.values(colors).slice(1).map(c=><i key={c} style={{background:c}}/>)}</div><div className="actions"><button>↑　위로 이동</button><button>↓　아래로 이동</button><button>▣　복제</button><button className="danger"><Trash2/> 노드 삭제</button></div></aside>}
function Graph(){const nodes=useMemo(()=>[...story,...ev.map(([id,x,y,title,meta,target])=>({id,type:'evidence',position:{x,y},data:{title,meta,target}}))],[]);const edges=useMemo(()=>{let main=story.slice(0,-1).map((n,i)=>({id:'m'+i,source:n.id,target:story[i+1].id,type:'smoothstep',className:'mainEdge'}));let side=ev.map(([id,x,y,t,m,target])=>({id:'l'+id,source:x<260?id:target,target:x<260?target:id,type:'smoothstep',className:'sideEdge'}));return [...main,...side]},[]);return <section className="graph"><div className="sectionHead"><b>Article Graph</b><div>↖　✋　100%　⌕　⛶　 <button>+ 노드 추가</button></div></div><div className="flow"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} defaultViewport={{x:30,y:0,zoom:.78}} minZoom={.35} maxZoom={1.5} panOnDrag fitView={false}><Background variant="dots" gap={18} size={1}/><MiniMap pannable zoomable/><Controls/></ReactFlow></div></section>}
function Live(){return <section className="live"><div className="sectionHead"><b>Live Article</b><div>◉ 미리보기　⛶ 전체화면</div></div><article><h1>{story[0].data.summary}</h1><div className="deck">도심 교통의 새로운 전환점… 안전성과 시민 체감도가 관건</div><div className="by">●　김민수 기자　 ◷ 2024. 11. 26. 10:24</div>{story.slice(1).map(n=>n.data.kind==='image'?<figure key={n.id}><div className="hero">서울 도심을 달리는 자율주행 버스</div><figcaption>{n.data.caption}</figcaption></figure>:<p key={n.id}>{n.data.body}</p>)}</article></section>}
export default function App(){return <div className="app"><header><div className="logo">NodeArticle <small>취재의 근거가 살아있는 글쓰기</small></div><div className="storyName">‹　 <b>서울시 자율주행 버스 시범운행 시작</b>　 <span>◉ 저장됨 · 10:24</span></div><nav><b>작성</b><span>자료</span><span>검증</span><span>히스토리</span><button>내보내기⌄</button><i>J</i></nav></header><main><Sources/><Graph/><Live/><Properties/></main></div>}
